extend type Query {
	products(
		order: SortDirection! = ASC
		orderBy: ProductSortBy! = DEFAULT
		search: String
		skip: Int! = 0
		take: Int! = 10
	): ProductList!
}

enum SortDirection {
	ASC
	DESC
}

enum ProductSortBy {
	DEFAULT
	NAME
	PRICE
	RATING
}

type ListMeta {
	count: Int!
	total: Int!
}

type ProductList {
	data: [Product!]!
	meta: ListMeta!
}
